### ISSUE TITLE
Matrix version

### ISSUE THREAD

**Issue by yeahme49** [mintsoft/kodi.plugin.ytchannels#2]
Now that the plugin got accepted into the Leia repo, will you submit to the Matrix repo as well? Just need to change the python line in addon.xml to 3.0.0 and change plugin version to add +matrix.1 to the end of the version number. Thanks.

Edit: If you create a matrix branch I can make a pull request for the addon.xml changes and also update the settings.xml file to the new settings file format for Matrix.

**Comment by mintsoft** [comment]
Yeah I can do that. I was under the impression that it being in the Leia repo will automatically pull into the Matrix repo? 
Or are you saying that there needs to be changes to keep it compatible with Matrix?

If there are changes needed I'll make a branch for the Matrix compatibility and we can maintain it like that

**Comment by yeahme49** [comment]
Since Leia uses Python 2 and Matrix uses Python 3, even if an addon is cross-compatible between the two versions, there are still changes that need to be made in the addon.xml file for it to get merged into the Matrix repo.

**Comment by mintsoft** [comment]
Makes sense, I've made a matrix branch for those changes then: https://github.com/mintsoft/kodi.plugin.ytchannels/tree/matrix

**Comment by mintsoft** [comment]
Should have those changes in now @yeahme49

**Comment by yeahme49** [comment]
I submitted a PR that uses the new settings.xml format. Only other issue I noticed was the version was 0.2.1+matrix. Looking through the forums and other addons it appears 0.2.1+matrix.1 would be the recommended way to put it, so I changed that in my PR as well. After that I think it should be all set to submit to the matrix repo.

**Comment by mintsoft** [comment]
PR is here: https://github.com/xbmc/repo-plugins/pull/3012/
