### ISSUE TITLE
Can't get version 0.4.0 into the main repo currently

### ISSUE THREAD

**Issue by mintsoft** [mintsoft/kodi.plugin.ytchannels#26]
FYI @yeahme49 The Kodi guys won't merge this in with invidious as a dependency as it's not in their repository: https://github.com/xbmc/repo-plugins/pull/3847#issuecomment-1019113987

I've raised an issue with invidious to see if they're willing to PR it in: https://github.com/TheAssassin/kodi-invidious-plugin/issues/10 as the Kodi guys have suggested.

Short of that, I might have to remove the invidious option, maybe we maintain a branch with that in which isn't the one that the repo uses?

**Comment by yeahme49** [comment]
I'd be fine with removing the invidious option to get it into the kodi repo. Could always have a second option available for download on here that adds invidious. I don't actually use it but I came across it and thought it might be a second option for people. But I'd rather just remove it and get this version onthe kodi repo.
