### ISSUE TITLE
YouTube live stream video always freezes after loading spinner, but audio keeps playing

### ISSUE THREAD

**Issue by sryze** [mintsoft/kodi.plugin.ytchannels#30]
It seems like there is a bug in the YouTube live stream player - I noticed that after each time it shows a loading spinner (due to buffering on slow network or connection issue or whatever), the video does not continue playing, but the audio does. 

The only workaround that I know of is to exit the player and restart. There is no pause/play button for some reason?

**Comment by mintsoft** [comment]
Interesting, the YTChannels plugin essentially delegates playing to the Kodi YouTube addon. If you find the same stream through the search in there, does it do the same thing? Assuming it does, you're probably best checking for bug there and raising one with a specific stream and the kodi.log. https://github.com/anxdpanic/plugin.video.youtube is where it lives

**Comment by sryze** [comment]
Thanks, I will try to reproduce it with the YouTube addon

**Comment by sryze** [comment]
Yep, it has the same issue. I'll open an issue there instead. Thanks!
