### ISSUE TITLE
Channel list is not refreshed after adding a channel to root

### ISSUE THREAD

**Issue by sryze** [mintsoft/kodi.plugin.ytchannels#32]
Sometimes after I add a channel to the root folder, the list of channels does not get refreshed and the new channel is not added to it, so I can't watch it right away.

I don't know what causes it exactly, but I noticed that it often happens to me when I add a first channel after a fresh install of Kodi and this addon. But it does not happen 100% of the time.

**Comment by mintsoft** [comment]
I have also seen this. I am 99% sure this is something to do with the ordering; i.e. it's inserted the new folder/channel into the middle of a list and it's out of whack. I think it might only happen in the situation where you have either deleted a channel or re-ordered/organised the channels then added one; however I've not got a solid reproduction case yet.

**Comment by sryze** [comment]
Could it have something to do with how SQLite saves data to the DB? It seems like there is some sort of race, like as if Container.Refresh is called before the channel is fully saved to DB... I found very little documentation on Container.Refresh, and I still have no idea how it is different from Container.Update.

**Comment by mintsoft** [comment]
I'm 99% sure it's the DB state that's wrong. Before we introduced the ability to reorder the channels, I never saw it; whereas now I see it from time to time. What I really need is to get a reproduction case and then have a look at the database; I bet there's a gap in the "order" column

**Comment by mintsoft** [comment]
I've just experienced this when adding into subfolders as well, so it's not limited to just the root.. Given the number of items in the subfolder I was adding, I don't think it is the DB state either

**Comment by mintsoft** [comment]
Just experienced this again, I've taken the time to investigate this time and I have two different channels with the same "sort". I'm going to completly change how this is implemented and implement a "sort A-Z" option on the menu so we can "fix" anything that's wrong

**Comment by mintsoft** [comment]
Sussed it out, it should be fixed in: https://github.com/mintsoft/kodi.plugin.ytchannels/pull/39
