### ISSUE TITLE
content not available on this app - change in user-agent

### ISSUE THREAD

**Issue by mcarni** [mintsoft/kodi.plugin.ytchannels#35]
i could not access any video due to youtube saying that the content was not available
i followed some instructions for another kodi addon and I played around with the user-agent
i basically modified functions.py
and replaced the two instances of user-agent from:
`Mozilla/5.0 (Windows NT 6.1; rv:33.0) Gecko/20100101 Firefox/33.0`
to `Mozilla/5.0 (Android 13; Mobile; rv:68.0) Gecko/68.0 Firefox/112.0`

not sure if this could be a permanent fix, but it seems to be working fine so far

M

**Comment by mintsoft** [comment]
Thanks, I've just got round to replying to your message on the forum. I'll make that change, or you can Pull-Request it in yourself if you would prefer?

**Comment by mcarni** [comment]
i forked your repo, modified the file and pull a request... let me know if it works...

**Comment by mintsoft** [comment]
Yep that's perfect

**Comment by mintsoft** [comment]
0.4.4 includes this change and will hopefully have fewer issues with "content not available" errors

**Comment by mintsoft** [comment]
0.4.4 has been released into the KODI addons repo now; it normally takes about 24 hrs before that appears for me in librelec

**Comment by mintsoft** [comment]
OK so 0.4.4 doesn't improve things for me. I've found that if I find a video through the YouTube app that doesn't work through YT channels; it also doesn't work. I'm pretty sure this is going to be a global problem with Kodi and Youtube. There is a huge thread on the youtube addon: https://github.com/anxdpanic/plugin.video.youtube/issues/442

**Comment by mintsoft** [comment]
Closing as it's not an issue with ytchannels, it's the youtube addon
