### ISSUE TITLE
Unnecessary YouTube id listings in Kodi log

### ISSUE THREAD

**Issue by jirkoun** [mintsoft/kodi.plugin.ytchannels#43]
I use YTChannel as a source for several widgets and I have to say that Youtube id listings are quite annoying. The list of those ids is completely useless, it does not carry any useful information and just makes the log less clear with unnecessary ballast.

Today, in the **functions.py** module in **def get_latest_from_channel()**, all ids are logged (with LOGINFO status) and then once again separately those that do not pass the "short videos" filter (conditionally, if this filter is set).

I can think of two ways to solve this:
1. Add a condition enabling/disabling (perhaps default as disabling) this logging to the plugin settings - but this seems to me to be an unnecessary complication and especially lay users will not fully realize what it is actually there for
2. Simply change the status of both log entries to LOGDEBUG - after all, I still think that log entry is only there for debugging purposes

**Comment by mintsoft** [comment]
Yep, those logs are definitely there for only for debugging, I'll just rip them out

**Comment by mintsoft** [comment]
https://github.com/xbmc/repo-plugins/pull/4420
